site_name: SiDE Documentation
pages:
- Home: index.md
- Intro:
    - About: about.md
- User Manual:
    - Panel: manual/panel.md
    - Desktop: manual/desktop.md
    - Tools:
        - Editor: manual/editor.md
        - View: manual/view.md 
- Developer:
    - Plugins: plugins.md
theme: readthedocs
repo_url: http://github.com/jetspace/desktop
site_author: Marius Messerschmidt
